initial commit
taro-kuroda-5228/cross_val_practice pull request #1
Opened 2022-02-09 23:43 UTC by taro-kuroda-5228

タスク1006です！

2022-02-09 23:52 UTC, atsushimemet requested changes
@taro-kuroda-5228 
いくつか関数・クラスに分割して、コード全体の見通しをよくしましょう!
最後にmain関数を作成して、コマンドラインから呼びだせるようにしましょう。

2022-02-10 05:36 UTC, taro-kuroda-5228 commented
すいません、main関数というのはif __name__ == '__main__'のことですか？？

2022-02-10 12:27 UTC, atsushimemet approved these changes
@taro-kuroda-5228 
main関数は一旦なしでOKです。
このコードを書いたのは一体誰なんでしょう、素晴らしすぎて絶句しました 笑
コードをクラスにまとめ直すのが、かなり上手になっているようです。
とてもとても嬉しい限りです。
+1

2022-02-11 00:37 UTC, taro-kuroda-5228 commented
了解しました！
小澤さんの御指導のおかげです！ありがとうございます！😂

2022-02-11 00:37 UTC, merged